In [8]:
import numpy as np
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [20]:
np.zeros(6, dtype = np.int32)

array([0, 0, 0, 0, 0, 0])

In [13]:
# ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
# Empty
np.empty(6, dtype = np.int32)

array([0, 0, 0, 0, 0, 0])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [17]:
#linspace
np.linspace(1, 100, num = 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [19]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

## Array's Functions


In [23]:
a = np.array([2,10,15,12,6,100 ,200,0.5, 10.3])
a

array([  2. ,  10. ,  15. ,  12. ,   6. , 100. , 200. ,   0.5,  10.3])

In [25]:
# sorting
a.sort()
a

array([  0.5,   2. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. , 200. ])

In [32]:
# Concatenating the array
b = np.array([10.4, 3.2, 53.6, 91.6,55])
b
c=np.concatenate((a,b))
c.sort()
c

array([  0.5,   2. ,   3.2,   6. ,  10. ,  10.3,  10.4,  12. ,  15. ,
        53.6,  55. ,  91.6, 100. , 200. ])

## Two Dimensional Arrays

In [33]:
a=np.array([[1,2,3,4,5],[6,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [6, 4, 3, 2, 1]])

In [34]:
b = np.array([[1,4,5,6,7],[3,5,7,8,9]])
b

array([[1, 4, 5, 6, 7],
       [3, 5, 7, 8, 9]])

In [35]:
# Concatenating
c = np.concatenate((a,b), axis = 0)
c

array([[1, 2, 3, 4, 5],
       [6, 4, 3, 2, 1],
       [1, 4, 5, 6, 7],
       [3, 5, 7, 8, 9]])

In [36]:
c.size

20

In [38]:
a.shape

(2, 5)

In [40]:
c = c.reshape(5,4)
c

array([[1, 2, 3, 4],
       [5, 6, 4, 3],
       [2, 1, 1, 4],
       [5, 6, 7, 3],
       [5, 7, 8, 9]])

In [41]:
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b.shape

(1, 9)

In [44]:
b= a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
a[2:6]

array([3, 4, 5, 6])

In [46]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

## NumPy Practice for Numpy documentation